### ISSUE TITLE
Provide a definition?

### ISSUE THREAD

**Issue by BertrandCaron** [PREMIS-OWL-Revision-Team/premis-owl#24]
https://github.com/PREMIS-OWL-Revision-Team/revise-premis-owl/blob/498ba82180fd3cbc92e0dbe5bbaf6f12b05fcbf8/premis3.owl#L288

I proposed something here: https://docs.google.com/document/d/18xKq2MGBfY1St0Wlva4WCdsrELtzIS1o7Gt1B7pDpxs/edit#bookmark=id.f78m9lm5xr3e

**Comment by rguenther52** [comment]
Looks good to me.
And great to put comments in the ontology saying not yet published.

Rebecca
