### ISSUE TITLE
Can we assert this?

### ISSUE THREAD

**Issue by BertrandCaron** [PREMIS-OWL-Revision-Team/premis-owl#26]
https://github.com/PREMIS-OWL-Revision-Team/revise-premis-owl/blob/498ba82180fd3cbc92e0dbe5bbaf6f12b05fcbf8/premis3.owl#L351

At some point, we considered using dce:rights (don't ask me why, I'm a little bit confused...). If we use dce:rights, we can't declare premis:governs as inverse property, right?

**Comment by escowles** [comment]
If we make this `inverseOf` declaration, then it implies that we think the domain of `dcterms:rights` is `premis:Object` and the range is `premis:RightsStatus` (i.e., that `premis:RightsStatus` is the same as `dcterms:RightsStatus`).  So we should probably remove this.
