### ISSUE TITLE
Domain should be premis:Object and premis:Agent.

### ISSUE THREAD

**Issue by BertrandCaron** [PREMIS-OWL-Revision-Team/premis-owl#33]
https://github.com/PREMIS-OWL-Revision-Team/revise-premis-owl/blob/498ba82180fd3cbc92e0dbe5bbaf6f12b05fcbf8/premis3.owl#L472

**Comment by rguenther52** [comment]
I agree-- this is in the list of changes for id.loc.gov relationshipSubType (expanding the definition).
