### ISSUE TITLE
replace :hasNote with skos:note

### ISSUE THREAD

**Issue by marshallduval** [PREMIS-OWL-Revision-Team/premis-owl#50]

**Comment by BertrandCaron** [comment]
premis:hasNote is not meant to be an annotation property like skos;note is. Instead, premis:hasNote and its subproperties are intended to be used for unstructured information about a resource (for example, http://www.loc.gov/standards/premis/v3/premis-3-0-final.pdf#page=108).
Note that we will make changes to the PREMIS Data Dictionary in its further version to fix the problems the RDF expression made obvious.
