### ISSUE TITLE
replace :hasSize with ebucore:fileByteSize or define relation with skos

### ISSUE THREAD

**Issue by marshallduval** [PREMIS-OWL-Revision-Team/premis-owl#54]

**Comment by BertrandCaron** [comment]
We preferred not to use ebucore:fileSize because the 'size' PREMIS semantic unit also applies to bitstreams (though the range of the property is MediaResource, which could probably be a suitable super-class for premis:File and premis:Bitstream).

I'll add a SKOS mapping property to it, anyway.
