### ISSUE TITLE
hasMedium should not be subproperty of dct:medium

### ISSUE THREAD

**Issue by BertrandCaron** [PREMIS-OWL-Revision-Team/premis-owl#60]
Because domain of dcterms:medium is dct:PhysicalResource.

https://github.com/PREMIS-OWL-Revision-Team/revise-premis-owl/blob/c78d10ec6cebfff59ca3cbccd1d33734ee209ef6/premis3.owl#L406

**Comment by rguenther52** [comment]
I am not sure why this is so in dct. There is also the class dct:MediaType ("a file format or physical medium"), of which dct:PhysicalMedium is a subclass. dct:FileFormat is also a subclass of dct:MediaType.  dct:medium is a subproperty of dc:format, which is "the file format, physical medium or dimensions". I thought that dct:medium could be either an electronic or physical format and refines format to separate medium and extent. However, I see in the User Guide (which seems to not be maintained and is at https://github.com/dcmi/repository/tree/master/mediawiki_wiki/User_Guide) it says that dct:medium isn't used for file format but only for physical media. That means that the only property that can be used for file formats is dc:format, but it is so general that it can be format OR extent, i.e. either a string or a URI (which I thought you couldn't do). I think I'll ask for clarification from DCMI. Unless someone else can explain it.

**Comment by rguenther52** [comment]
Note that the DCMI Usage Board discussed my comments, but only in regards to the ISO standard (which doesn't standardize the RDF but only the elements and their definitions).  At this point it is best to just remove the subproperty assertion (as Bertrand has done) and perhaps later we will want to add it back if it gets changed in dcterms.
