### ISSUE TITLE
Shouldn't this property be renamed to "hasMediumType"?

### ISSUE THREAD

**Issue by BertrandCaron** [PREMIS-OWL-Revision-Team/premis-owl#61]
Indeed, you cannot instantiate a premis:StorageMedium to describe a specific magnetic tape (in the PREMIS DD, storageMedium points to a controlled vocab - don't know why it's not called storageMediumType like the other ones, btw.

https://github.com/PREMIS-OWL-Revision-Team/revise-premis-owl/blob/c78d10ec6cebfff59ca3cbccd1d33734ee209ef6/premis3.owl#L404

**Comment by rguenther52** [comment]
storageMedium is defined as essentially "the physical medium on which the object is stored". We use types when we associate it with other semantic units in a container. The vocab could be renamed, but I'm not sure that's necessary.

**Comment by BertrandCaron** [comment]
As it is now, the data dictionary suggests that the expected value of storageMedium should be a storage type (put another way, we expect it to be based on a controlled vocabulary: "magnetic tape", "CD-ROM", etc., not a value like "magnetic_tape_00001" that would indicate an instance of a magnetic tape). If we follow strictly the DD, we would have a "hasMediumType" property pointing to instances of Medium that would be storMedium:mag.

But in the proposed changes for id.loc.gov, we suggest that the members of the storageMedium vocab should be subclasses, not instances, of premis:Medium. That implies that users are encouraged to declare objects of premis:hasMedium as instances of this vocab, i.e. that we would expect instances of premis:Medium to be locally declared as the concrete media on which the Object is stored. We would expect as the object of hasMedium something like my:magnetic-tape-00001, which would be an instance of storMedium:mag.

We therefore suggest that it is in the scope of PREMIS to provide means to describe the storage units, whereas in the DD, the scope of PREMIS is limited to the storage type. So the ontology would be slightly ahead of the DD - but I think it is OK. I just wanted to point this issue to the group. I will close this issue, unless someone wants to add a different point of view.
