### ISSUE TITLE
Different URIs for premis 

### ISSUE THREAD

**Issue by gatemezing** [PREMIS-OWL-Revision-Team/premis-owl#72]
Hello,
I've just seen that the new URI for Premis V3 is this one http://www.loc.gov/premis/rdf/v3/, different from the first version tracked in LOV at https://lov.linkeddata.es/dataset/lov/vocabs/premis (v1). How are all these versions related? I also see in one example here https://github.com/PREMIS-OWL-Revision-Team/revise-premis-owl/blob/master/examples/raw_image.ttl that the prefix premis uses a different URI http://id.loc.gov/vocabulary/preservation. Would you clarify all these different namespaces for developers or consumers already using the first version of the vocabulary? Thx!

**Comment by rguenther52** [comment]
The new version 3 ontology supports PREMIS Data Dictionary version 3 and the previous one (called version 1) supported PREMIS DD version 2.2. The URIs aren't active yet under http://www.loc.gov/premis/rdf/v3/ but will be soon. There are controlled vocabularies that have relationships with the PREMIS v3 ontology and they are at http://id.loc.gov/vocabulary/preservation/. These also are in the process of being updated, and when they are, there will be assertions relating to the PREMIS ontology, e.g. a member of the list is a subclass of a class in the ontology, etc. See: http://www.loc.gov/standards/premis/ontology/owl-version3.html for supporting documentation.

**Comment by gatemezing** [comment]
Thanks @rguenther52  for this detailed explanation. Please, let me know when all those URIs are active to be able to add them into LOV.

**Comment by BertrandCaron** [comment]
The examples are now corrected, see https://github.com/PREMIS-OWL-Revision-Team/revise-premis-owl/pull/73
