### ISSUE TITLE
examples/disk_image.ttl: Why is <diskImageE01> a premis:Representation?

### ISSUE THREAD

**Issue by dla-kramski** [PREMIS-OWL-Revision-Team/premis-owl#77]
I'm a complete PREMIS noob and just diving into this kind of stuff, but it seems to me that <diskImageE01> on line 130 should be a premis:File, not a premis:Representation.

**Comment by dla-kramski** [comment]
... that "diskImageE01" on line 130... ("tag" has been dropped).

**Comment by BertrandCaron** [comment]
Thank you for catching this! It has been corrected.
